name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3 # This action helps us to cache in Github's cloud space
        with:
          path: ~/.npm  # Node uses this folder in linux to cache dependencies
          # Specify a key with dynamic value
          # Dynamic value here = Calculate a hash based on package-lock json file
          # If contents of package-lock json file changes, a newer cache will be created
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci # If cache available, use. Else install
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      # If caching is already done in earlier job, it'll not be done here again
      - name: Cache dependencies
        uses: actions/cache@v3 
        with:
          path: ~/.npm  
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploying..."
